/* eslint-disable max-len */
const data = {
  total_pages: 2,
  total_results: 28,
  results: [
    {
      id: 49051,
      name: 'The Hobbit: An Unexpected Journey',
      overview: 'Bilbo Baggins, a hobbit enjoying his quiet life, is swept into an epic quest by Gandalf the Grey and thirteen dwarves who seek to reclaim their mountain home from Smaug, the dragon.',
      popularity: 77.967,
      poster: '/yHA9Fc37VmpUA5UncTxxo3rTGVA.jpg',
      release: '2012-11-26',
      voteAverage: 7.3,
      voteCount: 15087,
      site: '',
      imdb: '',
    },
    {
      id: 122917,
      name: 'The Hobbit: The Battle of the Five Armies',
      overview: "Immediately after the events of The Desolation of Smaug, Bilbo and the dwarves try to defend Erebor's mountain of treasure from others who claim it: the men of the ruined Laketown and the elves of Mirkwood. Meanwhile an army of Orcs led by Azog the Defiler is marching on Erebor, fueled by the rise of the dark lord Sauron. Dwarves, elves and men must unite, and the hope for Middle-Earth falls into Bilbo's hands.",
      popularity: 126.111,
      poster: '/xT98tLqatZPQApyRmlPL12LtiWp.jpg',
      release: '2014-12-10',
      voteAverage: 7.3,
      voteCount: 11231,
      site: '',
      imdb: '',
    },
    {
      id: 57158,
      name: 'The Hobbit: The Desolation of Smaug',
      overview: 'The Dwarves, Bilbo and Gandalf have successfully escaped the Misty Mountains, and Bilbo has gained the One Ring. They all continue their journey to get their gold back from the Dragon, Smaug.',
      popularity: 62.318,
      poster: '/xQYiXsheRCDBA39DOrmaw1aSpbk.jpg',
      release: '2013-12-11',
      voteAverage: 7.6,
      voteCount: 10280,
      site: '',
      imdb: '',
    },
    {
      id: 1362,
      name: 'The Hobbit',
      overview: "Bilbo Baggins the Hobbit was just minding his own business, when his occasional visitor Gandalf the Wizard drops in one night. One by one, a whole group of dwarves drop in, and before he knows it, Bilbo has joined their quest to reclaim their kingdom, taken from them by the evil dragon Smaug. The only problem is that Gandalf has told the dwarves that Bilbo is an expert burglar, but he isn't...",
      popularity: 14.734,
      poster: '/2ohvyMPhvjftLrM6S6Ljr6QrL0u.jpg',
      release: '1977-11-27',
      voteAverage: 6.3,
      voteCount: 189,
      site: '',
      imdb: '',
    },
  ],
  page: 1,
  totalPages: 2,
};

export default data;
